-- Seed characters: anime, movie, book
INSERT INTO characters (name, type, franchise, image_url) VALUES
-- Anime
('Naruto Uzumaki',   'anime', 'Naruto',              'https://cdn.myanimelist.net/images/characters/2/284121.jpg'),
('Sasuke Uchiha',    'anime', 'Naruto',              'https://cdn.myanimelist.net/images/characters/9/131317.jpg'),
('Monkey D. Luffy',  'anime', 'One Piece',           'https://cdn.myanimelist.net/images/characters/9/310307.jpg'),
('Roronoa Zoro',     'anime', 'One Piece',           'https://cdn.myanimelist.net/images/characters/3/100534.jpg'),
('Nami',             'anime', 'One Piece',           'https://cdn.myanimelist.net/images/characters/5/100524.jpg'),
('Son Goku',         'anime', 'Dragon Ball',         'https://cdn.myanimelist.net/images/characters/15/72534.jpg'),
('Vegeta',           'anime', 'Dragon Ball',         'https://cdn.myanimelist.net/images/characters/1/72537.jpg'),
('Levi Ackerman',    'anime', 'Attack on Titan',     'https://cdn.myanimelist.net/images/characters/2/241413.jpg'),
('Mikasa Ackerman',  'anime', 'Attack on Titan',     'https://cdn.myanimelist.net/images/characters/9/215563.jpg'),
('Eren Yeager',      'anime', 'Attack on Titan',     'https://cdn.myanimelist.net/images/characters/10/215562.jpg'),
('Edward Elric',     'anime', 'Fullmetal Alchemist', 'https://cdn.myanimelist.net/images/characters/11/174117.jpg'),
('Roy Mustang',      'anime', 'Fullmetal Alchemist', 'https://cdn.myanimelist.net/images/characters/9/174132.jpg'),
('Light Yagami',     'anime', 'Death Note',          'https://cdn.myanimelist.net/images/characters/11/174641.jpg'),
('L Lawliet',        'anime', 'Death Note',          'https://cdn.myanimelist.net/images/characters/9/83105.jpg'),
('Itachi Uchiha',    'anime', 'Naruto',              'https://cdn.myanimelist.net/images/characters/8/131322.jpg'),
('Killua Zoldyck',   'anime', 'Hunter x Hunter',     'https://cdn.myanimelist.net/images/characters/7/53219.jpg'),
('Gon Freecss',      'anime', 'Hunter x Hunter',     'https://cdn.myanimelist.net/images/characters/9/55548.jpg'),
('Ichigo Kurosaki',  'anime', 'Bleach',              'https://cdn.myanimelist.net/images/characters/16/353257.jpg'),
('Tanjiro Kamado',   'anime', 'Demon Slayer',        'https://cdn.myanimelist.net/images/characters/10/407927.jpg'),
('Nezuko Kamado',    'anime', 'Demon Slayer',        'https://cdn.myanimelist.net/images/characters/10/407927.jpg'),
-- Movie / TV
('Tony Stark',       'movie', 'Iron Man / MCU',       'https://upload.wikimedia.org/wikipedia/en/4/47/Iron_Man_%282008_film%29_poster.jpg'),
('Steve Rogers',     'movie', 'Captain America / MCU','https://upload.wikimedia.org/wikipedia/en/6/60/Captain_America_The_First_Avenger_poster.jpg'),
('Natasha Romanoff', 'movie', 'Black Widow / MCU',    'https://upload.wikimedia.org/wikipedia/en/0/02/Black_Widow_%282021_film%29_poster.jpg'),
('Thor Odinson',     'movie', 'Thor / MCU',           'https://upload.wikimedia.org/wikipedia/en/f/fd/Thor_2011_film_poster.jpg'),
('T''Challa',        'movie', 'Black Panther / MCU',  'https://upload.wikimedia.org/wikipedia/en/4/4b/Black_Panther_film_poster.jpg'),
('Hermione Granger', 'movie', 'Harry Potter',         'https://upload.wikimedia.org/wikipedia/en/8/8c/Hermione_Granger_poster.jpg'),
('Harry Potter',     'movie', 'Harry Potter',         'https://upload.wikimedia.org/wikipedia/en/e/e9/Harry_Potter_and_the_Philosopher%27s_Stone.jpg'),
('Daenerys Targaryen','movie','Game of Thrones',       'https://upload.wikimedia.org/wikipedia/en/1/12/Game_of_Thrones_title_card.jpg'),
('Jon Snow',         'movie', 'Game of Thrones',      'https://upload.wikimedia.org/wikipedia/en/1/12/Game_of_Thrones_title_card.jpg'),
('Arya Stark',       'movie', 'Game of Thrones',      'https://upload.wikimedia.org/wikipedia/en/1/12/Game_of_Thrones_title_card.jpg'),
('Frodo Baggins',    'movie', 'The Lord of the Rings','https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg'),
('Aragorn',          'movie', 'The Lord of the Rings','https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg'),
('Katniss Everdeen', 'movie', 'The Hunger Games',     'https://upload.wikimedia.org/wikipedia/en/4/42/HungerGamesPoster.jpg'),
('Neo',              'movie', 'The Matrix',           'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg'),
('Ethan Hunt',       'movie', 'Mission: Impossible',  'https://upload.wikimedia.org/wikipedia/en/9/9c/Mission_Impossible_1996_film_poster.jpg'),
-- Book
('Elizabeth Bennet', 'book',  'Pride & Prejudice',    'https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg'),
('Mr. Darcy',        'book',  'Pride & Prejudice',    'https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg'),
('Atticus Finch',    'book',  'To Kill a Mockingbird','https://upload.wikimedia.org/wikipedia/en/7/79/To_Kill_a_Mockingbird.JPG'),
('Jay Gatsby',       'book',  'The Great Gatsby',     'https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg'),
('Sherlock Holmes',  'book',  'Sherlock Holmes',      'https://upload.wikimedia.org/wikipedia/commons/c/cd/Strand_paget.jpg'),
('Holden Caulfield', 'book',  'The Catcher in the Rye','https://upload.wikimedia.org/wikipedia/commons/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg'),
('Tyrion Lannister', 'book',  'A Song of Ice and Fire','https://upload.wikimedia.org/wikipedia/en/1/12/Game_of_Thrones_title_card.jpg'),
('Ender Wiggin',     'book',  'Ender''s Game',         'https://upload.wikimedia.org/wikipedia/en/e/e4/Ender%27s_game_cover_ISBN_0_312_93208_1.jpg'),
('Samwise Gamgee',   'book',  'The Lord of the Rings', 'https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg'),
('Percy Jackson',    'book',  'Percy Jackson',         'https://upload.wikimedia.org/wikipedia/en/c/c2/PercyJacksonLightningThief.jpg');
