CREATE TABLE IF NOT EXISTS passes (
  passer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  passed_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (passer_id, passed_id)
);
